Controller specs
Busiwa24/Blog-App pull request #2
Opened 2022-01-14 18:30 UTC by Busiwa24

2022-01-14 19:48 UTC, Dipeshtwis requested changes
Hi @Busiwa24, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
 
**_Check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 19:48 UTC, Dipeshtwis commented on spec/controller_test/posts_controller_spec.rb
> +  end
- [ ] I would recommend adding the test for the `Post#show` as well.

2022-01-14 19:48 UTC, Dipeshtwis commented on spec/controller_test/users_controller_spec.rb
> +  end
- [ ] I would recommend adding the test for the `Users#show` as well.

2022-01-14 20:07 UTC, Busiwa24 commented on spec/controller_test/posts_controller_spec.rb
> +  end
resolved

2022-01-14 20:07 UTC, Busiwa24 commented on spec/controller_test/users_controller_spec.rb
> +  end
fixed

2022-01-14 20:25 UTC, oloomoses requested changes
Hi @Busiwa24, 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 20:25 UTC, oloomoses commented on spec/controller_test/users_controller_spec.rb
> +  end
- [ ] As suggested in the previous review by @Dipeshtwis, Kindly add spec test for the `user#show` the same way you did with `index`. This means that you will add another `describe` block for `#show`.

2022-01-14 20:25 UTC, oloomoses commented on spec/controller_test/posts_controller_spec.rb
> +  end
- [ ] As suggested in the previous review by @Dipeshtwis, Kindly add spec test for the `post#show` the same way you did with `index`. This means that you will add another `describe` block for `#post`.

2022-01-15 09:53 UTC, DeliceLydia approved these changes
# Status: Approved🎉🎉

## Hi @Busiwa24, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-15 14:39 UTC, merged