Queries
Busiwa24/Blog-App pull request #4
Opened 2022-01-18 17:39 UTC by Busiwa24

2022-01-18 19:10 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Busi, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
Git flow is followed. :heavy_check_mark:
README is professional. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-18 19:10 UTC, SajjadAhmad14 commented on app/models/user.rb
> +  has_many :likes, dependent: :destroy
Please add `author_id` as a foreign key to Post, Comment, and Like models instead of user_id as it is shown in ERD [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png).
`has_many :posts, foreign_key: 'author_id'`
`has_many :comments, foreign_key: 'author_id'`
`has_many :likes, foreign_key: 'author_id'`

2022-01-18 19:10 UTC, SajjadAhmad14 commented on app/models/post.rb
> +  belongs_to :user
A Post should belong to an `Author` which references the `User` class.
``belongs_to :author, class_name: 'User'``

2022-01-18 19:10 UTC, SajjadAhmad14 commented on app/models/comment.rb
> +  belongs_to :user
A Comment should belong to an `Author` which references the `User` class.
``belongs_to :author, class_name: 'User'``

2022-01-18 19:10 UTC, SajjadAhmad14 commented on app/models/like.rb
> +  belongs_to :user
A Like should belong to an `Author` which references the `User` class.
``belongs_to :author, class_name: 'User'``

2022-01-18 19:10 UTC, SajjadAhmad14 commented on app/models/user.rb
> +class User < ApplicationRecord
The user is unable to set up the database as there are some duplicate migrations. KIndly try to set your project up locally and remove the duplicate migrations.

2022-01-19 12:35 UTC, Busiwa24 commented on app/models/user.rb
> +  has_many :likes, dependent: :destroy
resolved

2022-01-19 12:35 UTC, Busiwa24 commented on app/models/post.rb
> +  belongs_to :user
resolved

2022-01-19 12:40 UTC, Busiwa24 commented on app/models/comment.rb
> +  belongs_to :user
resolved

2022-01-19 12:43 UTC, Busiwa24 commented on app/models/like.rb
> +  belongs_to :user
resolved

2022-01-19 12:51 UTC, Busiwa24 commented on app/models/user.rb
> +class User < ApplicationRecord
resolved

2022-01-19 13:10 UTC, ElijahTobs approved these changes
# STATUS: APPROVED 🎉 🥇 
## Hi @Busiwa24 👋  

Good job making the changes required by the previous Code Reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

#### "Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

_Reviewed by_: __**Elijah Ayandokun**__

2022-01-19 13:25 UTC, merged