Add form
Busiwa24/Blog-App pull request #6
Opened 2022-01-21 14:57 UTC by Busiwa24

2022-01-21 15:37 UTC, AshakaE requested changes
### Hi @Busiwa24  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._

###  Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 15:37 UTC, AshakaE commented on app/controllers/posts_controller.rb
> +  end
- [ ] Kindly initialize a new post with the 'new` method, instead of setting current_user which already exits across your application controller

2022-01-21 15:37 UTC, AshakaE commented on app/controllers/comments_controller.rb
> +  end
- [ ] Please add a `new` method and initialize a `comment`

2022-01-21 21:43 UTC, ElijahTobs requested changes
# Status: Changes Required ⚠️ 🚦
## Hi @Busiwa24  👋

You've done really well so far! 👍 

## Major Highlights 💯 


Your README is professional ✔️ 
Github flow rules followed ✔️ 
You have good commit messages ✔️ 
All linter checks pass ✔️ 

_However, there are some changes that you are required to make before this project can be approved._

## Required Changes ♻️


_See the inline comments below_


_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

#### "Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
## Happy Coding :computer: 

_Reviewed by_  **Elijah O. Ayandokun**

2022-01-21 21:43 UTC, ElijahTobs commented on app/controllers/posts_controller.rb
> +  end
- [ ] Here in the posts controller, you're expected to initialize a new post, not a new comment.

2022-01-21 21:43 UTC, ElijahTobs commented on app/controllers/comments_controller.rb
> +  end
- [ ] Kindly add a `new` method to initialize a `comment` as stated by the previous reviewer

2022-01-21 21:43 UTC, ElijahTobs commented on app/controllers/posts_controller.rb
> +  end
- [ ] ___[OPTIONAL]___ This `create` method here should be for creating posts, not comments

2022-01-22 11:05 UTC, uwadonat approved these changes
Hi @Busiwa24, 

Your project is complete! Congratulations on your efforts. 
![good-job](https://user-images.githubusercontent.com/65860678/150635865-d40f2c03-b4d7-4750-b8b8-b4ba41f29eee.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-22 12:54 UTC, merged